# Generated by Django 3.0.5 on 2020-06-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subject_detail',
            fields=[
                ('subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.register')),
            ],
        ),
    ]
