# Generated by Django 3.0.5 on 2020-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_register_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerAdmin',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
