# Generated by Django 3.0.5 on 2020-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20200619_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulk_register',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('profile_pic', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=200)),
                ('room_number', models.CharField(blank=True, default='', max_length=200)),
                ('subjects', models.TextField(blank=True)),
            ],
        ),
    ]
